import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";

const adarsh = "https://i.ibb.co/QN1NmRj/adarsh-balika.jpg";
const bruce = "https://i.ibb.co/R0sRR6Q/bruce-wayne.jpg";
const john = "https://i.ibb.co/TmYfHXq/john-wick.jpg";
const shubham = "https://i.ibb.co/5rTX8xX/shubham-soni.jpg";
const tanay = "https://i.ibb.co/LvVryfK/tanay-pratap.jpg";

/**
 * Posts can be added here.
 * You can add default posts of your wish with different attributes
 * */

export const posts = [
  {
    // _id: uuid(),
    _id: "1abc-2xyz-3pqr",
    content: "Start where you are. Use what you have. Do what you can.",
    likes: {
      likeCount: 1,
      likedBy: [
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "shubham",
          followers: [],
          following: [],
          // id: "1",
          lastName: "soni",
          password: "shubhamsoni",
          updatedAt: formatDate(),
          username: "shubhamsoni",
          avatar: shubham,
          _id: uuid(),
        },
      ],
      dislikedBy: [],
    },
    username: "adarshbalika",
    firstName: "Adarsh",
    lastName: "Balika",
    createdAt: "01/05/2023",
    avatar: adarsh,
    updatedAt: formatDate(),
  },
  {
    // _id: uuid(),
    _id: "2abc-2xyz-3pqr",
    content:
      "SAFF Championship 2023 Final, India Vs Kuwait: India Win On Penalties After Match Ended 1-1 In Regulation Time",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    username: "shubhamsoni",
    avatar: shubham,
    firstName: "shubham",
    lastName: "soni",
    createdAt: "11/15/2021",
    updatedAt: formatDate(),
  },
  {
    // _id: uuid(),
    _id: "3abc-2xyz-3pqr",
    content: "Dark Knight Rises, Gotham is in Safe hands",
    likes: {
      likeCount: 3,
      likedBy: [
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "Adarsh",
          avatar: adarsh,
          followers: [],
          following: [],
          // id: "1",
          lastName: "Balika",
          password: "adarshBalika123",
          updatedAt: formatDate(),
          username: "adarshbalika",
          _id: uuid(),
        },
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "Tanay",
          avatar: tanay,
          followers: [],
          following: [],
          // id: "1",
          lastName: "Pratap",
          password: "tanayPratap",
          updatedAt: formatDate(),
          username: "tanayPratap",
          _id: uuid(),
        },
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "shubham",
          avatar: shubham,
          followers: [],
          following: [],
          // id: "1",
          lastName: "soni",
          password: "shubhamsoni",
          updatedAt: formatDate(),
          username: "shubhamsoni",
          _id: uuid(),
        },
      ],
      dislikedBy: [],
    },
    username: "brucewayne",
    firstName: "Bruce",
    avatar: bruce,
    lastName: "Wayne",
    createdAt: "04/04/2019",
    updatedAt: formatDate(),
  },
  {
    // _id: uuid(),
    _id: "4abc-2xyz-3pqr",
    content:
      "You gotta be a fighter to be a lover, If you don't fight for your love, what kind of love is it?",
    likes: {
      likeCount: 4,
      likedBy: [
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "Adarsh",
          followers: [],
          following: [],
          avatar: adarsh,
          // id: "1",
          lastName: "Balika",
          password: "adarshBalika123",
          updatedAt: formatDate(),
          username: "adarshbalika",
          _id: uuid(),
        },
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "Tanay",
          avatar: tanay,
          followers: [],
          following: [],
          // id: "1",
          lastName: "Pratap",
          password: "tanayPratap",
          updatedAt: formatDate(),
          username: "tanayPratap",
          _id: uuid(),
        },
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "shubham",
          avatar: shubham,
          followers: [],
          following: [],
          // id: "1",
          lastName: "soni",
          password: "shubhamsoni",
          updatedAt: formatDate(),
          username: "shubhamsoni",
          _id: uuid(),
        },
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "Bruce",
          avatar: bruce,
          followers: [],
          following: [],
          // id: "1",
          lastName: "Wayne",
          password: "brucewayne",
          updatedAt: formatDate(),
          username: "brucewayne",
          _id: uuid(),
        },
      ],
      dislikedBy: [],
    },
    username: "johnwick",
    firstName: "John",
    avatar: john,
    lastName: "Wick",
    createdAt: "06/05/2023",
    updatedAt: formatDate(),
  },
  {
    // _id: uuid(),
    _id: "5abc-2xyz-3pqr",
    content: "Being the Mentor I never had.",
    likes: {
      likeCount: 3,
      likedBy: [
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "Bruce",
          avatar: bruce,
          followers: [],
          following: [],
          // id: "1",
          lastName: "Wayne",
          password: "brucewayne",
          updatedAt: formatDate(),
          username: "brucewayne",
          _id: uuid(),
        },
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "Adarsh",
          avatar: adarsh,
          followers: [],
          following: [],
          // id: "1",
          lastName: "Balika",
          password: "adarshBalika123",
          updatedAt: formatDate(),
          username: "adarshbalika",
          _id: uuid(),
        },
        {
          bookmarks: [],
          createdAt: formatDate(),
          firstName: "John",
          avatar: john,
          followers: [],
          following: [],
          // id: "1",
          lastName: "Wick",
          password: "johnwick",
          updatedAt: formatDate(),
          username: "johnwick",
          _id: uuid(),
        },
      ],
      dislikedBy: [],
    },
    username: "tanayPratap",
    firstName: "Tanay",
    avatar: tanay,
    lastName: "Pratap",
    createdAt: "12/31/2022",
    updatedAt: formatDate(),
  },
];
